### ISSUE TITLE
403 Forbidden in pretrained model website

### ISSUE THREAD

**Issue by Qi-X** [yz93/anchor-diff-VOS#11]
I encounter "You don't have permission to access this resource." when I visit the pretrained weights' website.
Could you please help me get the pretrained model? Thanks.

**Comment by yz93** [comment]
This one should work.
https://drive.google.com/file/d/1A6ozn2FT2Ef1dn7HGNgUb1WboWFN2NON/view?usp=sharing
Many thanks!
