### ISSUE TITLE
All of the Pre-computed maps seems to be background maps.

### ISSUE THREAD

**Issue by EnQing626** [yz93/anchor-diff-VOS#8]
Very thanks for sharing your code. But when I download the Pre-computed results, each map is the background map. Could you upload the Pre-computed results again? Thank you~

**Comment by yz93** [comment]
Those were saved without a pallete. Weren't intended to serve as visualizations. Sorry about the inconvenience.

Should be easy to add a pallete to it after opening and then re-save.
