### ISSUE TITLE
Do not understand "unsupervised"

### ISSUE THREAD

**Issue by EricFH** [yz93/anchor-diff-VOS#9]
hello, after reading your paper, I don't understand how to train the model.
In experiment section, "binary cross-entropy loss" is mentioned, it seems the network should be trained with pixel-wise supervised label like segmentation.
Could you show the "unsupervised process" with detail? Thank you.

**Comment by yz93** [comment]
Right. "Unsupervised" here was a terminology for VOS only and was different than what it generally means in machine learning context. The way it is used can be quite confusing and misleading.

It is a fully supervised method and requires GT masks for training. "Unsupervised" only refers to the setup during test time, which is no GT initialization is given before inference starts.

Many thanks.
